server:
  port: 8088

spring:
  application:
    name: api-driver

  redis:
    host: 121.37.71.228
    port: 6380
    database: 2
    password: foobared

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public