server:
  port: 8086

spring:
  application:
    name: service-driver-user

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.37.71.228:3308/taxi_driver?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  #type-aliases-package: com.erato.internalcommon.dto

logging:
  level:
    com.erato.servicedriveruser.dao: debug